env: cityflow

env_args:
  # key: "config/envs/Hangzhou/4_4/config.json"
  key: "config/envs/Jinan/3_4/config.json"
  # key: "config/envs/NewYork/16_3/config.json"
  # key: "config/envs/NewYork/28_7/config.json"
  # key: "config/envs/SH1/config.json"
  # key: "config/envs/SH2/config.json"
  time_limit: 100
  pretrained_wrapper: null
  add_sight_id_len: null
  episode_limit: 3600
  default_sight: 1

test_greedy: True
test_nepisode: 2
test_interval: 50000
log_interval: 50000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 2050000
