domain: LBF
parent: null
seeds: [ 0, 1, 2, 3, 4 ]

hp_all_skip: # 所有 alg 都跳過檢查的超參數。為 list of str。
  - t_max
  - save_path
  - buffer_cpu_only
  - seed # 這裡不用設，因為別處有特別檢查 seed
  - local_results_path
  - name
  - reset_pos
  - save_model
  - save_model_interval
  - save_replay
  - use_cuda
  - use_tensorboard
  - render
  - force_render
  # 對於以下 FAS 設定的 TODO: 未來多一個欄位，檢查若有此變數，要什麼值才可以；若不存在，則skip
  - use_fas
  - fas_lambda
  - fas_dynamic

hp_all:
  add_value_last_step: [ True ]
  agent: [ "rnn" ]
  batch_size: [ 32 ]
  reset_buffer_after_switch_visibility: [ False ]
  force_render: [ False ]
  checkpoint_path: [ "" ] # Train from scratch
  env_args:
    add_sight_id_len: [ null ]
    key: [ ]
    pretrained_wrapper: [ null ]
    time_limit: [ 50 ]
  evaluate: [ False ]
  gamma: [ 0.99 ]
  grad_norm_clip: [ 10.0 ]
  env: [ 'gymma' ]
  hypergroup: [ null ]
  label: [ 'default_label' ]
  runner_log_interval: [ 10000 ]
  learner_log_interval: [ 10000 ]
  load_step: [ 0 ]
  log_interval: [ 50000 ]
  mac: [ 'basic_mac' ]
  n_distillation_grad_steps: [ 0 ]
  n_grad_steps: [ 1 ]
  n_offline_grad_steps: [ 0 ]
  optim_alpha: [ 0.99 ]
  optim_eps: [ !!float 1e-05 ]
  preprocess_desc: [ null ]
  redo_freq: [ 0 ]
  redo_tau: [ 0 ]
  repeat_id: [ 1 ]
  reset_freq: [ 0 ]
  test_greedy: [ True ]
  test_nepisode: [ 100 ]
  train_next_visibility: [ False ]
  turn_off_train_preprocess: [ False ]
  weight_decay: [ 0.0 ]
  reset_after_switch_visibility: [ False ]
  dormant_all_taus: [ [ 0, 0.0001, 0.001, 0.01 ] ]
  offline_buffer_path: [ null ]
  offline_buffer_grad_steps: [ 100 ]
  policy_diff_n_batches: [ 32 ]
  dormant_n_batches: [ 32 ]
  dormant_check_interval: [ 0 ]
  policy_diff_interval_1: [ 0 ]
  policy_diff_interval_2: [ 0 ]
  policy_diff_interval_3: [ 0 ]

hp_alg_group:
  value-based:
    action_selector: [ "epsilon_greedy" ]
    epsilon_start: [ 1.0 ]
    epsilon_finish: [ 0.05 ]
    epsilon_anneal_time: [ 200000 ]
    evaluation_epsilon: [ 0.05 ]
    runner: [ "episode" ]
    buffer_size: [ 5000 ]
    target_update_interval_or_tau: [ 200 ]
    obs_agent_id: [ True ]
    obs_last_action: [ False ]
    obs_individual_obs: [ False ]
    agent_output_type: [ "q" ]
    learner: [ "q_learner" ]
    standardise_returns: [ False ]
    standardise_rewards: [ True ]
    double_q: [ True ]
    use_rnn: [ True ]
    lr: [ 0.0003 ]
    hidden_dim: [ 128 ]
    batch_size_run: [ 1 ]
    test_interval: [ 50000 ]
  ppo:
    hidden_dim: [ 64 ]
    action_selector: [ "soft_policies" ]
    mask_before_softmax: [ True ]
    runner: [ "parallel" ]
    buffer_size: [ 10 ]
    batch_size_run: [ 10 ]
    batch_size: [ 10 ]
    lr: [ 0.0003 ]
    obs_agent_id: [ True ]
    obs_last_action: [ False ]
    obs_individual_obs: [ False ]
    agent_output_type: [ "pi_logits" ]
    learner: [ "ppo_learner" ]
    entropy_coef: [ 0.001 ]
    use_rnn: [ True ]
    standardise_returns: [ False ]
    standardise_rewards: [ False ]
    q_nstep: [ 5 ]
    epochs: [ 4 ]
    eps_clip: [ 0.2 ]
    test_interval: [ 50000 ]


hp_alg:
  iql:
    min_n_tests: 101 # 1M
    hyperparameter_group: value-based
    custom_hyperparameters: { mixer: [ null ] }
    not_having_ok_hyperparameters:
      - force_render
      - train_next_visibility # 預設是不使用，所以沒有specify也不影響
      - reset_buffer_after_switch_visibility # 預設是不使用，所以沒有specify也不影響
      - offline_buffer_path
      - offline_buffer_grad_steps
  vdn:
    min_n_tests: 101 # 1M
    hyperparameter_group: value-based
    custom_hyperparameters: { mixer: [ vdn ] }
    not_having_ok_hyperparameters:
      - force_render
      - train_next_visibility # 預設是不使用，所以沒有specify也不影響
      - reset_buffer_after_switch_visibility # 預設是不使用，所以沒有specify也不影響
      - offline_buffer_path
      - offline_buffer_grad_steps
  qmix:
    min_n_tests: 101 # 1M
    hyperparameter_group: value-based
    custom_hyperparameters: { mixer: [ qmix ], mixing_embed_dim: [ 32 ], hypernet_layers: [ 2 ],hypernet_embed: [ 64 ] }
    not_having_ok_hyperparameters:
      - force_render
      - train_next_visibility # 預設是不使用，所以沒有specify也不影響
      - reset_buffer_after_switch_visibility # 預設是不使用，所以沒有specify也不影響
      - offline_buffer_path
      - offline_buffer_grad_steps
  ippo:
    min_n_tests: 101
    hyperparameter_group: ppo
    custom_hyperparameters: { critic_type: [ "ac_critic" ], target_update_interval_or_tau: [ 200 ] }
    not_having_ok_hyperparameters:
      - offline_buffer_path
      - offline_buffer_grad_steps
  mappo:
    min_n_tests: 101
    hyperparameter_group: ppo
    custom_hyperparameters: { critic_type: [ "cv_critic" ], target_update_interval_or_tau: [ 0.01 ] }
    not_having_ok_hyperparameters:
      - offline_buffer_path
      - offline_buffer_grad_steps

hp_map_sight:
  10s-10x10-4p-2f-v1:
    2s: { env_args: { key: [ lbforaging:Foraging-2s-10x10-4p-2f-v1 ] } , preprocess_desc: [ null ] }
    4s: { env_args: { key: [ lbforaging:Foraging-4s-10x10-4p-2f-v1 ] } , preprocess_desc: [ null ] }
    6s: { env_args: { key: [ lbforaging:Foraging-6s-10x10-4p-2f-v1 ] } , preprocess_desc: [ null ] }
    8s: { env_args: { key: [ lbforaging:Foraging-8s-10x10-4p-2f-v1 ] } , preprocess_desc: [ null ] }
    10s: { env_args: { key: [ lbforaging:Foraging-10s-10x10-4p-2f-v1 ] } , preprocess_desc: [ null ] }
    "ucb(2,4,6,8,10)_0919": { env_args: { key: [ lbforaging:Foraging-10s-10x10-4p-2f-v1 ] } , preprocess_desc: [ "lbf:10s->ucb(2s,4s,6s,8s,10s),c=2,w=5000" ] }
  6s-10x10-4p-2f-v1:
    2s: { env_args: { key: [ lbforaging:Foraging-2s-10x10-4p-2f-v1 ] } , preprocess_desc: [ null ] }
    4s: { env_args: { key: [ lbforaging:Foraging-4s-10x10-4p-2f-v1 ] } , preprocess_desc: [ null ] }
    6s: { env_args: { key: [ lbforaging:Foraging-6s-10x10-4p-2f-v1 ] } , preprocess_desc: [ null ] }
    "ucb(2,4,6)_0919": { env_args: { key: [ lbforaging:Foraging-6s-10x10-4p-2f-v1 ] } , preprocess_desc: [ "lbf:6s->ucb(2s,4s,6s),c=2,w=5000" ] }
  10s-10x10-4p-4f-v1:
    2s: { env_args: { key: [ lbforaging:Foraging-2s-10x10-4p-4f-v1 ] } , preprocess_desc: [ null ] }
    4s: { env_args: { key: [ lbforaging:Foraging-4s-10x10-4p-4f-v1 ] } , preprocess_desc: [ null ] }
    6s: { env_args: { key: [ lbforaging:Foraging-6s-10x10-4p-4f-v1 ] } , preprocess_desc: [ null ] }
    8s: { env_args: { key: [ lbforaging:Foraging-8s-10x10-4p-4f-v1 ] } , preprocess_desc: [ null ] }
    10s: { env_args: { key: [ lbforaging:Foraging-10s-10x10-4p-4f-v1 ] } , preprocess_desc: [ null ] }
    "ucb(2,4,6,8,10)_0919": { env_args: { key: [ lbforaging:Foraging-10s-10x10-4p-4f-v1 ] } , preprocess_desc: [ "lbf:10s->ucb(2s,4s,6s,8s,10s),c=2,w=5000" ] }
  10s-10x10-4p-4f-coop-v1:
    2s: { env_args: { key: [ lbforaging:Foraging-2s-10x10-4p-4f-coop-v1 ] } , preprocess_desc: [ null ] }
    4s: { env_args: { key: [ lbforaging:Foraging-4s-10x10-4p-4f-coop-v1 ] } , preprocess_desc: [ null ] }
    6s: { env_args: { key: [ lbforaging:Foraging-6s-10x10-4p-4f-coop-v1 ] } , preprocess_desc: [ null ] }
    8s: { env_args: { key: [ lbforaging:Foraging-8s-10x10-4p-4f-coop-v1 ] } , preprocess_desc: [ null ] }
    10s: { env_args: { key: [ lbforaging:Foraging-10s-10x10-4p-4f-coop-v1 ] } , preprocess_desc: [ null ] }
    "ucb(2,4,6,8,10)_0919": { env_args: { key: [ lbforaging:Foraging-10s-10x10-4p-4f-coop-v1 ] } , preprocess_desc: [ "lbf:10s->ucb(2s,4s,6s,8s,10s),c=2,w=5000" ] }
  10s-10x10-4p-2f-coop-v1:
    2s: { env_args: { key: [ lbforaging:Foraging-2s-10x10-4p-2f-coop-v1 ] } , preprocess_desc: [ null ] }
    4s: { env_args: { key: [ lbforaging:Foraging-4s-10x10-4p-2f-coop-v1 ] } , preprocess_desc: [ null ] }
    6s: { env_args: { key: [ lbforaging:Foraging-6s-10x10-4p-2f-coop-v1 ] } , preprocess_desc: [ null ] }
    8s: { env_args: { key: [ lbforaging:Foraging-8s-10x10-4p-2f-coop-v1 ] } , preprocess_desc: [ null ] }
    10s: { env_args: { key: [ lbforaging:Foraging-10s-10x10-4p-2f-coop-v1 ] } , preprocess_desc: [ null ] }
    "ucb(2,4,6,8,10)_0919": { env_args: { key: [ lbforaging:Foraging-10s-10x10-4p-2f-coop-v1 ] } , preprocess_desc: [ "lbf:10s->ucb(2s,4s,6s,8s,10s),c=2,w=5000" ] }
  6s-10x10-4p-4f-v1:
    2s: { env_args: { key: [ lbforaging:Foraging-2s-10x10-4p-4f-v1 ] } , preprocess_desc: [ null ] }
    4s: { env_args: { key: [ lbforaging:Foraging-4s-10x10-4p-4f-v1 ] } , preprocess_desc: [ null ] }
    6s: { env_args: { key: [ lbforaging:Foraging-6s-10x10-4p-4f-v1 ] } , preprocess_desc: [ null ] }
    "ucb(2,4,6)_0919": { env_args: { key: [ lbforaging:Foraging-6s-10x10-4p-4f-v1 ] } , preprocess_desc: [ "lbf:6s->ucb(2s,4s,6s),c=2,w=5000" ] }
  6s-10x10-4p-4f-coop-v1:
    2s: { env_args: { key: [ lbforaging:Foraging-2s-10x10-4p-4f-coop-v1 ] } , preprocess_desc: [ null ] }
    4s: { env_args: { key: [ lbforaging:Foraging-4s-10x10-4p-4f-coop-v1 ] } , preprocess_desc: [ null ] }
    6s: { env_args: { key: [ lbforaging:Foraging-6s-10x10-4p-4f-coop-v1 ] } , preprocess_desc: [ null ] }
    "ucb(2,4,6)_0919": { env_args: { key: [ lbforaging:Foraging-6s-10x10-4p-4f-coop-v1 ] } , preprocess_desc: [ "lbf:6s->ucb(2s,4s,6s),c=2,w=5000" ] }
  6s-10x10-4p-2f-coop-v1:
    2s: { env_args: { key: [ lbforaging:Foraging-2s-10x10-4p-2f-coop-v1 ] } , preprocess_desc: [ null ] }
    4s: { env_args: { key: [ lbforaging:Foraging-4s-10x10-4p-2f-coop-v1 ] } , preprocess_desc: [ null ] }
    6s: { env_args: { key: [ lbforaging:Foraging-6s-10x10-4p-2f-coop-v1 ] } , preprocess_desc: [ null ] }
    "ucb(2,4,6)_0919": { env_args: { key: [ lbforaging:Foraging-6s-10x10-4p-2f-coop-v1 ] } , preprocess_desc: [ "lbf:6s->ucb(2s,4s,6s),c=2,w=5000" ] }
  15s-15x15-3p-5f-v1:
    3s: { env_args: { key: [ lbforaging:Foraging-3s-15x15-3p-5f-v1 ] } , preprocess_desc: [ null ] }
    6s: { env_args: { key: [ lbforaging:Foraging-6s-15x15-3p-5f-v1 ] } , preprocess_desc: [ null ] }
    9s: { env_args: { key: [ lbforaging:Foraging-9s-15x15-3p-5f-v1 ] } , preprocess_desc: [ null ] }
    12s: { env_args: { key: [ lbforaging:Foraging-12s-15x15-3p-5f-v1 ] } , preprocess_desc: [ null ] }
    15s: { env_args: { key: [ lbforaging:Foraging-15s-15x15-3p-5f-v1 ] } , preprocess_desc: [ null ] }
    "ucb(3,6,9,12,15)_0919": { env_args: { key: [ lbforaging:Foraging-15s-15x15-3p-5f-v1 ] } , preprocess_desc: [ "lbf:15s->ucb(3s,6s,9s,12s,15s),c=2,w=5000" ] }
  6s-15x15-3p-5f-v1:
    2s: { env_args: { key: [ lbforaging:Foraging-2s-15x15-3p-5f-v1 ] } , preprocess_desc: [ null ] }
    4s: { env_args: { key: [ lbforaging:Foraging-4s-15x15-3p-5f-v1 ] } , preprocess_desc: [ null ] }
    6s: { env_args: { key: [ lbforaging:Foraging-6s-15x15-3p-5f-v1 ] } , preprocess_desc: [ null ] }
    "ucb(2,4,6)_0919": { env_args: { key: [ lbforaging:Foraging-6s-15x15-3p-5f-v1 ] } , preprocess_desc: [ "lbf:6s->ucb(2s,4s,6s),c=2,w=5000" ] }

hp_other_variables: { }


# --------------- Plotting Settings ---------------
# 畫之前請先跑 `check_exp.py` 確認沒有錯誤再執行 `plot_exp.py`
plot:
  templates:
    - template_name: 'LBF_template - base'
      exp_vars:
        alg: [ 'iql', 'vdn', 'qmix', 'ippo', 'mappo' ]
        map: [ '10s-10x10-4p-2f-v1', '6s-10x10-4p-2f-v1', '10s-10x10-4p-4f-v1', '6s-10x10-4p-4f-v1','10s-10x10-4p-2f-coop-v1', '6s-10x10-4p-2f-coop-v1', '10s-10x10-4p-4f-coop-v1', '6s-10x10-4p-4f-coop-v1', '15s-15x15-3p-5f-v1', '6s-15x15-3p-5f-v1' ]
        sight: [ 3s, 2s, 4s, 6s, 8s, 9s, 10s, 12s, 15s, "ucb(2,4,6,8,10)_0919", "ucb(2,4,6)_0919" , "ucb(3,6,9,12,15)_0919" ]
      skip_var_combinations: # Only leave the original one and the ucb one
        - alg: [ 'iql', 'vdn', 'qmix', 'ippo', 'mappo' ]
          map: [ '6s-10x10-4p-2f-v1', '6s-10x10-4p-4f-v1', '6s-10x10-4p-2f-coop-v1', '6s-10x10-4p-4f-coop-v1', '6s-15x15-3p-5f-v1' ]
          sight: [ 3s, 2s, 4s, 9s, 12s, 15s, 8s, 10s, "ucb(3,6,9,12,15)_0919", "ucb(2,4,6,8,10)_0919" ]
        - alg: [ 'iql', 'vdn', 'qmix', 'ippo', 'mappo' ]
          map: [ '10s-10x10-4p-2f-v1', '10s-10x10-4p-4f-v1', '10s-10x10-4p-2f-coop-v1', '10s-10x10-4p-4f-coop-v1' ]
          sight: [ 3s, 2s, 4s, 6s, 8s, 9s, 12s, 15s, "ucb(3,6,9,12,15)_0919", "ucb(2,4,6)_0919" ]
        - alg: [ 'iql', 'vdn', 'qmix', 'ippo', 'mappo' ]
          map: [ '15s-15x15-3p-5f-v1' ]
          sight: [ 3s, 6s, 9s, 12s, 2s, 4s, 6s, 8s, 10s, "ucb(2,4,6,8,10)_0919", "ucb(2,4,6)_0919" ]
      plot_config:
        title: 'template'
        save_path: 'lbf/0922_formal_5M/'
        tag: 'test_return_mean'
        band: 'std' # 'ci' or 'stderr' or 'minmax'
        plot_skip: 1
        y_low: -0.02
        y_high: 1.02
        ylabel: 'Test Return'
        base_width: 6
        base_height: 6
        no_show: True
        # 標註有哪些 pure sight (也可以不含)。這是用來輔助pure sight 深淺顏色的設定
        pure_sights: [ 2s, 3s, 4s, 6s, 8s, 9s, 10s, 12s, 15s ]
        #
        label_without_overall_performance: True
        label_without_len_and_runs: True
        hide_subtitle_description: False
        show_title: False
        show_legend: True
        show_text_on_line: False
        custom_ax_row_var: alg
        custom_ax_col_var: map
        row_var_order: [ 'iql', 'vdn', 'qmix', 'ippo', 'mappo' ]
        col_var_order: [ '10s-10x10-4p-2f-v1', '6s-10x10-4p-2f-v1', '10s-10x10-4p-4f-v1', '6s-10x10-4p-4f-v1','10s-10x10-4p-2f-coop-v1', '6s-10x10-4p-2f-coop-v1', '10s-10x10-4p-4f-coop-v1', '6s-10x10-4p-4f-coop-v1', '15s-15x15-3p-5f-v1', '6s-15x15-3p-5f-v1' ]
        list_of_assigned_styles_and_keywords:
          - { keywords: [ 'ucb' ], color: red }
  #          - { keywords: [ 'ucb', '0913' ], color: orange }
  #          - { keywords: [ 'ucb', 'before0913' ], color: green }


  plots:
    # ``python epy_tools/check_and_plot.py -f projects/LBF/sacred_others/20240913_比較並畫0913之前之後的UCB差異 -c epy_tools/check_exp_config/lbf/lbf_0913_afterUCBTestingFix.yml``
    #　===================== Return =====================
    # All pure sights and UCB
    - template_name: 'LBF_template - base'
      skip_var_combinations:
        - alg: [ 'iql', 'vdn', 'qmix', 'ippo', 'mappo' ]
          map: [ '6s-10x10-4p-2f-v1', '6s-10x10-4p-4f-v1', '6s-10x10-4p-2f-coop-v1', '6s-10x10-4p-4f-coop-v1', '6s-15x15-3p-5f-v1' ]
          sight: [ 3s, 9s, 12s, 15s, 8s, 10s, "ucb(3,6,9,12,15)_0919", "ucb(2,4,6,8,10)_0919" ]
        - alg: [ 'iql', 'vdn', 'qmix', 'ippo', 'mappo' ]
          map: [ '10s-10x10-4p-2f-v1', '10s-10x10-4p-4f-v1', '10s-10x10-4p-2f-coop-v1', '10s-10x10-4p-4f-coop-v1' ]
          sight: [ 3s, 9s, 12s, 15s, "ucb(3,6,9,12,15)_0919", "ucb(2,4,6)_0919" ]
        - alg: [ 'iql', 'vdn', 'qmix', 'ippo', 'mappo' ]
          map: [ '15s-15x15-3p-5f-v1' ]
          sight: [ 2s, 4s, 6s, 8s, 10s, "ucb(2,4,6,8,10)_0919", "ucb(2,4,6)_0919" ]
      plot_config: { title: 'LBF - All Pure and UCB' }
    # Original sights and UCB
    - template_name: 'LBF_template - base'
      plot_config:
        title: 'LBF - Original vs UCB'
        list_of_assigned_styles_and_keywords:
          - { keywords: [ 's' ], color: black }
          - { keywords: [ 'ucb' ], color: red }
        label_without_len_and_runs: False
    #　===================== Sight =====================
    - template_name: 'LBF_template - base'
      exp_vars:
        sight: [ 2s, 4s, 8s, 10s, 3s, 6s, 9s, 12s, 15s, "ucb(2,4,6,8,10)_0919", "ucb(2,4,6)_0919", "ucb(3,6,9,12,15)_0919" ]
      skip_var_combinations:
        # 除去原本就不合理的組合
        - alg: [ 'iql', 'vdn', 'qmix', 'ippo', 'mappo' ]
          map: [ '6s-10x10-4p-2f-v1', '6s-10x10-4p-4f-v1', '6s-10x10-4p-2f-coop-v1', '6s-10x10-4p-4f-coop-v1', '6s-15x15-3p-5f-v1' ]
          sight: [ 3s, 2s, 4s, 9s, 12s, 15s, 8s, 10s, "ucb(3,6,9,12,15)_0919", "ucb(2,4,6,8,10)_0919" ]
        - alg: [ 'iql', 'vdn', 'qmix', 'ippo', 'mappo' ]
          map: [ '10s-10x10-4p-2f-v1', '10s-10x10-4p-4f-v1', '10s-10x10-4p-2f-coop-v1', '10s-10x10-4p-4f-coop-v1' ]
          sight: [ 3s, 2s, 4s, 6s, 8s, 9s, 12s, 15s, "ucb(3,6,9,12,15)_0919", "ucb(2,4,6)_0919" ]
        - alg: [ 'iql', 'vdn', 'qmix', 'ippo', 'mappo' ]
          map: [ '15s-15x15-3p-5f-v1' ]
          sight: [ 3s, 6s, 9s, 12s, 2s, 4s, 6s, 8s, 10s, "ucb(2,4,6,8,10)_0919", "ucb(2,4,6)_0919" ]
        # 再把 pure 都去掉
        - alg: [ 'iql', 'vdn', 'qmix', 'ippo', 'mappo' ]
          map: [ '10s-10x10-4p-2f-v1', '6s-10x10-4p-2f-v1', '10s-10x10-4p-4f-v1', '6s-10x10-4p-4f-v1','10s-10x10-4p-2f-coop-v1', '6s-10x10-4p-2f-coop-v1', '10s-10x10-4p-4f-coop-v1', '6s-10x10-4p-4f-coop-v1', '15s-15x15-3p-5f-v1', '6s-15x15-3p-5f-v1' ]
          sight: [ 2s, 3s, 4s, 6s, 8s, 9s, 10s, 12s, 15s ]
      plot_config:
        title: 'LBF - UCB Selected Sights'
        tag: 'test_selected_sight_mean'
        ylabel: 'Sight'
        y_high: null
        y_low: 0.98

