# --- IQL specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 200000
evaluation_epsilon: 0.05
runner: "episode"

buffer_size: 600 # each episode has 360 steps (if 1 hr = 3600 seconds, 10 seconds per step)
log_interval: 3600

# update the target network every {} episodes
target_update_interval_or_tau: 200

obs_agent_id: False
obs_last_action: False
obs_individual_obs: False

# use the Q_Learner to train

agent_output_type: "q"
learner: "q_learner"
standardise_returns: False
standardise_rewards: True
double_q: True
use_rnn: True
mixer: "vdn"


name: "ns_vdn"

lr: 0.0003
hidden_dim: 128

mac: "non_shared_mac"
agent: "rnn_ns"

dormant_check_interval: 0
policy_diff_interval_1: 0 # Compare the policy every {} gradient steps (if 0, not using policy diff)
policy_diff_interval_2: 0 # Compare the policy every {} gradient steps (if 0, not using policy diff)
policy_diff_interval_3: 0 # Compare the policy every {} gradient steps (if 0, not using policy diff)
test_nepisode: 10
